[build]
  base = "website/"
  publish = "public/"
  command = "echo 'default context'"
  functions = ".netlify/functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/micromdm/micromdm"

[context.production]
  command = "make netlify"

